backend:
  name: github
  repo: Peresadka-project/zander-museum
  branch: main
  auth_scope: "repo"

media_folder: "public/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "pages"
    label: "Страницы"
    files:
      - file: "content/index.md"
        label: "Главная"
        name: "home"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }
          - { label: "Содержимое", name: "body", widget: "markdown" }

      - label: "Страница 404"
        name: "notfound"
        file: "content/404.md"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }
          - { label: "Текст", name: "body", widget: "markdown" }

  - name: "blog"
    label: "Блог"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime" }
      - { label: "Теги", name: "tags", widget: "list", required: false }
      - { label: "Текст", name: "body", widget: "markdown" }
